// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "i_max_pooling4.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic i_max_pooling4::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic i_max_pooling4::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> i_max_pooling4::ap_ST_fsm_state1 = "1";
const sc_lv<8> i_max_pooling4::ap_ST_fsm_state2 = "10";
const sc_lv<8> i_max_pooling4::ap_ST_fsm_state3 = "100";
const sc_lv<8> i_max_pooling4::ap_ST_fsm_state4 = "1000";
const sc_lv<8> i_max_pooling4::ap_ST_fsm_state5 = "10000";
const sc_lv<8> i_max_pooling4::ap_ST_fsm_state6 = "100000";
const sc_lv<8> i_max_pooling4::ap_ST_fsm_state7 = "1000000";
const sc_lv<8> i_max_pooling4::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> i_max_pooling4::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> i_max_pooling4::ap_const_lv32_1 = "1";
const sc_lv<1> i_max_pooling4::ap_const_lv1_0 = "0";
const sc_lv<32> i_max_pooling4::ap_const_lv32_2 = "10";
const sc_lv<32> i_max_pooling4::ap_const_lv32_3 = "11";
const sc_lv<32> i_max_pooling4::ap_const_lv32_4 = "100";
const sc_lv<32> i_max_pooling4::ap_const_lv32_5 = "101";
const sc_lv<32> i_max_pooling4::ap_const_lv32_6 = "110";
const sc_lv<32> i_max_pooling4::ap_const_lv32_7 = "111";
const sc_lv<5> i_max_pooling4::ap_const_lv5_0 = "00000";
const sc_lv<1> i_max_pooling4::ap_const_lv1_1 = "1";
const sc_lv<3> i_max_pooling4::ap_const_lv3_0 = "000";
const sc_lv<32> i_max_pooling4::ap_const_lv32_D368D4A5 = "11010011011010001101010010100101";
const sc_lv<2> i_max_pooling4::ap_const_lv2_0 = "00";
const sc_lv<5> i_max_pooling4::ap_const_lv5_10 = "10000";
const sc_lv<5> i_max_pooling4::ap_const_lv5_1 = "1";
const sc_lv<3> i_max_pooling4::ap_const_lv3_5 = "101";
const sc_lv<3> i_max_pooling4::ap_const_lv3_1 = "1";
const sc_lv<2> i_max_pooling4::ap_const_lv2_2 = "10";
const sc_lv<2> i_max_pooling4::ap_const_lv2_1 = "1";
const sc_lv<32> i_max_pooling4::ap_const_lv32_17 = "10111";
const sc_lv<32> i_max_pooling4::ap_const_lv32_1E = "11110";
const sc_lv<8> i_max_pooling4::ap_const_lv8_FF = "11111111";
const sc_lv<23> i_max_pooling4::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<5> i_max_pooling4::ap_const_lv5_2 = "10";
const bool i_max_pooling4::ap_const_boolean_1 = true;

i_max_pooling4::i_max_pooling4(sc_module_name name) : sc_module(name), mVcdFile(0) {
    lenet_top_fcmp_32dEe_U31 = new lenet_top_fcmp_32dEe<1,2,32,32,1>("lenet_top_fcmp_32dEe_U31");
    lenet_top_fcmp_32dEe_U31->clk(ap_clk);
    lenet_top_fcmp_32dEe_U31->reset(ap_rst);
    lenet_top_fcmp_32dEe_U31->din0(max_value_1_reg_144);
    lenet_top_fcmp_32dEe_U31->din1(input_r_q0);
    lenet_top_fcmp_32dEe_U31->ce(ap_var_for_const0);
    lenet_top_fcmp_32dEe_U31->opcode(ap_var_for_const1);
    lenet_top_fcmp_32dEe_U31->dout(grp_fu_167_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln104_1_fu_390_p2);
    sensitive << ( shl_ln104_1_reg_543 );
    sensitive << ( zext_ln103_fu_374_p1 );

    SC_METHOD(thread_add_ln104_2_fu_213_p2);
    sensitive << ( zext_ln104_2_fu_209_p1 );
    sensitive << ( zext_ln104_1_fu_197_p1 );

    SC_METHOD(thread_add_ln104_3_fu_329_p2);
    sensitive << ( add_ln104_2_reg_507 );
    sensitive << ( zext_ln104_3_fu_325_p1 );

    SC_METHOD(thread_add_ln104_4_fu_354_p2);
    sensitive << ( p_shl4_cast_fu_334_p3 );
    sensitive << ( zext_ln104_4_fu_350_p1 );

    SC_METHOD(thread_add_ln104_5_fu_399_p2);
    sensitive << ( add_ln104_4_reg_556 );
    sensitive << ( zext_ln104_5_fu_395_p1 );

    SC_METHOD(thread_add_ln104_fu_320_p2);
    sensitive << ( shl_ln_reg_525 );
    sensitive << ( zext_ln101_fu_304_p1 );

    SC_METHOD(thread_add_ln106_1_fu_261_p2);
    sensitive << ( add_ln106_reg_512 );
    sensitive << ( zext_ln106_1_fu_257_p1 );

    SC_METHOD(thread_add_ln106_2_fu_278_p2);
    sensitive << ( p_shl3_cast_fu_270_p3 );
    sensitive << ( zext_ln106_2_fu_266_p1 );

    SC_METHOD(thread_add_ln106_3_fu_364_p2);
    sensitive << ( add_ln106_2_reg_530 );
    sensitive << ( zext_ln106_3_fu_360_p1 );

    SC_METHOD(thread_add_ln106_fu_231_p2);
    sensitive << ( zext_ln104_fu_185_p1 );
    sensitive << ( zext_ln106_fu_227_p1 );

    SC_METHOD(thread_and_ln104_1_fu_486_p2);
    sensitive << ( and_ln104_fu_480_p2 );
    sensitive << ( grp_fu_167_p2 );

    SC_METHOD(thread_and_ln104_fu_480_p2);
    sensitive << ( or_ln104_fu_456_p2 );
    sensitive << ( or_ln104_1_fu_474_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln96_fu_173_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln96_fu_173_p2 );

    SC_METHOD(thread_bitcast_ln104_1_fu_427_p1);
    sensitive << ( input_load_reg_574 );

    SC_METHOD(thread_bitcast_ln104_fu_409_p1);
    sensitive << ( max_value_1_reg_144 );

    SC_METHOD(thread_c_fu_179_p2);
    sensitive << ( c_0_reg_86 );

    SC_METHOD(thread_h_fu_243_p2);
    sensitive << ( h_0_reg_97 );

    SC_METHOD(thread_i_fu_314_p2);
    sensitive << ( i_0_reg_133 );

    SC_METHOD(thread_icmp_ln101_fu_308_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i_0_reg_133 );

    SC_METHOD(thread_icmp_ln103_fu_378_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( j_0_reg_156 );

    SC_METHOD(thread_icmp_ln104_1_fu_450_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( trunc_ln104_fu_423_p1 );

    SC_METHOD(thread_icmp_ln104_2_fu_462_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_8_fu_430_p4 );

    SC_METHOD(thread_icmp_ln104_3_fu_468_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( trunc_ln104_1_fu_440_p1 );

    SC_METHOD(thread_icmp_ln104_fu_444_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_fu_413_p4 );

    SC_METHOD(thread_icmp_ln96_fu_173_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( c_0_reg_86 );

    SC_METHOD(thread_icmp_ln97_fu_237_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( h_0_reg_97 );

    SC_METHOD(thread_icmp_ln98_fu_284_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( w_0_reg_108 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln104_6_fu_404_p1 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_j_fu_384_p2);
    sensitive << ( j_0_reg_156 );

    SC_METHOD(thread_max_value_fu_492_p3);
    sensitive << ( input_load_reg_574 );
    sensitive << ( max_value_1_reg_144 );
    sensitive << ( and_ln104_1_fu_486_p2 );

    SC_METHOD(thread_or_ln104_1_fu_474_p2);
    sensitive << ( icmp_ln104_3_fu_468_p2 );
    sensitive << ( icmp_ln104_2_fu_462_p2 );

    SC_METHOD(thread_or_ln104_fu_456_p2);
    sensitive << ( icmp_ln104_1_fu_450_p2 );
    sensitive << ( icmp_ln104_fu_444_p2 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln106_4_fu_369_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( max_value_0_reg_120 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln101_fu_308_p2 );

    SC_METHOD(thread_p_shl3_cast_fu_270_p3);
    sensitive << ( add_ln106_1_fu_261_p2 );

    SC_METHOD(thread_p_shl4_cast_fu_334_p3);
    sensitive << ( add_ln104_3_fu_329_p2 );

    SC_METHOD(thread_shl_ln104_1_fu_296_p3);
    sensitive << ( w_0_reg_108 );

    SC_METHOD(thread_shl_ln_fu_249_p3);
    sensitive << ( h_0_reg_97 );

    SC_METHOD(thread_tmp_4_fu_201_p3);
    sensitive << ( c_0_reg_86 );

    SC_METHOD(thread_tmp_5_fu_219_p3);
    sensitive << ( c_0_reg_86 );

    SC_METHOD(thread_tmp_7_fu_342_p3);
    sensitive << ( add_ln104_3_fu_329_p2 );

    SC_METHOD(thread_tmp_8_fu_430_p4);
    sensitive << ( bitcast_ln104_1_fu_427_p1 );

    SC_METHOD(thread_tmp_fu_413_p4);
    sensitive << ( bitcast_ln104_fu_409_p1 );

    SC_METHOD(thread_tmp_s_fu_189_p3);
    sensitive << ( c_0_reg_86 );

    SC_METHOD(thread_trunc_ln104_1_fu_440_p1);
    sensitive << ( bitcast_ln104_1_fu_427_p1 );

    SC_METHOD(thread_trunc_ln104_fu_423_p1);
    sensitive << ( bitcast_ln104_fu_409_p1 );

    SC_METHOD(thread_w_fu_290_p2);
    sensitive << ( w_0_reg_108 );

    SC_METHOD(thread_zext_ln101_fu_304_p1);
    sensitive << ( i_0_reg_133 );

    SC_METHOD(thread_zext_ln103_fu_374_p1);
    sensitive << ( j_0_reg_156 );

    SC_METHOD(thread_zext_ln104_1_fu_197_p1);
    sensitive << ( tmp_s_fu_189_p3 );

    SC_METHOD(thread_zext_ln104_2_fu_209_p1);
    sensitive << ( tmp_4_fu_201_p3 );

    SC_METHOD(thread_zext_ln104_3_fu_325_p1);
    sensitive << ( add_ln104_fu_320_p2 );

    SC_METHOD(thread_zext_ln104_4_fu_350_p1);
    sensitive << ( tmp_7_fu_342_p3 );

    SC_METHOD(thread_zext_ln104_5_fu_395_p1);
    sensitive << ( add_ln104_1_fu_390_p2 );

    SC_METHOD(thread_zext_ln104_6_fu_404_p1);
    sensitive << ( add_ln104_5_fu_399_p2 );

    SC_METHOD(thread_zext_ln104_fu_185_p1);
    sensitive << ( c_0_reg_86 );

    SC_METHOD(thread_zext_ln106_1_fu_257_p1);
    sensitive << ( h_0_reg_97 );

    SC_METHOD(thread_zext_ln106_2_fu_266_p1);
    sensitive << ( add_ln106_1_fu_261_p2 );

    SC_METHOD(thread_zext_ln106_3_fu_360_p1);
    sensitive << ( w_0_reg_108 );

    SC_METHOD(thread_zext_ln106_4_fu_369_p1);
    sensitive << ( add_ln106_3_fu_364_p2 );

    SC_METHOD(thread_zext_ln106_fu_227_p1);
    sensitive << ( tmp_5_fu_219_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln96_fu_173_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln97_fu_237_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln98_fu_284_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln101_fu_308_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln103_fu_378_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "00000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "i_max_pooling4_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, c_fu_179_p2, "c_fu_179_p2");
    sc_trace(mVcdFile, c_reg_502, "c_reg_502");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, add_ln104_2_fu_213_p2, "add_ln104_2_fu_213_p2");
    sc_trace(mVcdFile, add_ln104_2_reg_507, "add_ln104_2_reg_507");
    sc_trace(mVcdFile, icmp_ln96_fu_173_p2, "icmp_ln96_fu_173_p2");
    sc_trace(mVcdFile, add_ln106_fu_231_p2, "add_ln106_fu_231_p2");
    sc_trace(mVcdFile, add_ln106_reg_512, "add_ln106_reg_512");
    sc_trace(mVcdFile, h_fu_243_p2, "h_fu_243_p2");
    sc_trace(mVcdFile, h_reg_520, "h_reg_520");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, shl_ln_fu_249_p3, "shl_ln_fu_249_p3");
    sc_trace(mVcdFile, shl_ln_reg_525, "shl_ln_reg_525");
    sc_trace(mVcdFile, icmp_ln97_fu_237_p2, "icmp_ln97_fu_237_p2");
    sc_trace(mVcdFile, add_ln106_2_fu_278_p2, "add_ln106_2_fu_278_p2");
    sc_trace(mVcdFile, add_ln106_2_reg_530, "add_ln106_2_reg_530");
    sc_trace(mVcdFile, w_fu_290_p2, "w_fu_290_p2");
    sc_trace(mVcdFile, w_reg_538, "w_reg_538");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, shl_ln104_1_fu_296_p3, "shl_ln104_1_fu_296_p3");
    sc_trace(mVcdFile, shl_ln104_1_reg_543, "shl_ln104_1_reg_543");
    sc_trace(mVcdFile, icmp_ln98_fu_284_p2, "icmp_ln98_fu_284_p2");
    sc_trace(mVcdFile, i_fu_314_p2, "i_fu_314_p2");
    sc_trace(mVcdFile, i_reg_551, "i_reg_551");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, add_ln104_4_fu_354_p2, "add_ln104_4_fu_354_p2");
    sc_trace(mVcdFile, add_ln104_4_reg_556, "add_ln104_4_reg_556");
    sc_trace(mVcdFile, icmp_ln101_fu_308_p2, "icmp_ln101_fu_308_p2");
    sc_trace(mVcdFile, j_fu_384_p2, "j_fu_384_p2");
    sc_trace(mVcdFile, j_reg_564, "j_reg_564");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, icmp_ln103_fu_378_p2, "icmp_ln103_fu_378_p2");
    sc_trace(mVcdFile, input_load_reg_574, "input_load_reg_574");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, max_value_fu_492_p3, "max_value_fu_492_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, c_0_reg_86, "c_0_reg_86");
    sc_trace(mVcdFile, h_0_reg_97, "h_0_reg_97");
    sc_trace(mVcdFile, w_0_reg_108, "w_0_reg_108");
    sc_trace(mVcdFile, max_value_0_reg_120, "max_value_0_reg_120");
    sc_trace(mVcdFile, i_0_reg_133, "i_0_reg_133");
    sc_trace(mVcdFile, max_value_1_reg_144, "max_value_1_reg_144");
    sc_trace(mVcdFile, j_0_reg_156, "j_0_reg_156");
    sc_trace(mVcdFile, zext_ln106_4_fu_369_p1, "zext_ln106_4_fu_369_p1");
    sc_trace(mVcdFile, zext_ln104_6_fu_404_p1, "zext_ln104_6_fu_404_p1");
    sc_trace(mVcdFile, tmp_s_fu_189_p3, "tmp_s_fu_189_p3");
    sc_trace(mVcdFile, tmp_4_fu_201_p3, "tmp_4_fu_201_p3");
    sc_trace(mVcdFile, zext_ln104_2_fu_209_p1, "zext_ln104_2_fu_209_p1");
    sc_trace(mVcdFile, zext_ln104_1_fu_197_p1, "zext_ln104_1_fu_197_p1");
    sc_trace(mVcdFile, tmp_5_fu_219_p3, "tmp_5_fu_219_p3");
    sc_trace(mVcdFile, zext_ln104_fu_185_p1, "zext_ln104_fu_185_p1");
    sc_trace(mVcdFile, zext_ln106_fu_227_p1, "zext_ln106_fu_227_p1");
    sc_trace(mVcdFile, zext_ln106_1_fu_257_p1, "zext_ln106_1_fu_257_p1");
    sc_trace(mVcdFile, add_ln106_1_fu_261_p2, "add_ln106_1_fu_261_p2");
    sc_trace(mVcdFile, p_shl3_cast_fu_270_p3, "p_shl3_cast_fu_270_p3");
    sc_trace(mVcdFile, zext_ln106_2_fu_266_p1, "zext_ln106_2_fu_266_p1");
    sc_trace(mVcdFile, zext_ln101_fu_304_p1, "zext_ln101_fu_304_p1");
    sc_trace(mVcdFile, add_ln104_fu_320_p2, "add_ln104_fu_320_p2");
    sc_trace(mVcdFile, zext_ln104_3_fu_325_p1, "zext_ln104_3_fu_325_p1");
    sc_trace(mVcdFile, add_ln104_3_fu_329_p2, "add_ln104_3_fu_329_p2");
    sc_trace(mVcdFile, tmp_7_fu_342_p3, "tmp_7_fu_342_p3");
    sc_trace(mVcdFile, p_shl4_cast_fu_334_p3, "p_shl4_cast_fu_334_p3");
    sc_trace(mVcdFile, zext_ln104_4_fu_350_p1, "zext_ln104_4_fu_350_p1");
    sc_trace(mVcdFile, zext_ln106_3_fu_360_p1, "zext_ln106_3_fu_360_p1");
    sc_trace(mVcdFile, add_ln106_3_fu_364_p2, "add_ln106_3_fu_364_p2");
    sc_trace(mVcdFile, zext_ln103_fu_374_p1, "zext_ln103_fu_374_p1");
    sc_trace(mVcdFile, add_ln104_1_fu_390_p2, "add_ln104_1_fu_390_p2");
    sc_trace(mVcdFile, zext_ln104_5_fu_395_p1, "zext_ln104_5_fu_395_p1");
    sc_trace(mVcdFile, add_ln104_5_fu_399_p2, "add_ln104_5_fu_399_p2");
    sc_trace(mVcdFile, bitcast_ln104_fu_409_p1, "bitcast_ln104_fu_409_p1");
    sc_trace(mVcdFile, bitcast_ln104_1_fu_427_p1, "bitcast_ln104_1_fu_427_p1");
    sc_trace(mVcdFile, tmp_fu_413_p4, "tmp_fu_413_p4");
    sc_trace(mVcdFile, trunc_ln104_fu_423_p1, "trunc_ln104_fu_423_p1");
    sc_trace(mVcdFile, icmp_ln104_1_fu_450_p2, "icmp_ln104_1_fu_450_p2");
    sc_trace(mVcdFile, icmp_ln104_fu_444_p2, "icmp_ln104_fu_444_p2");
    sc_trace(mVcdFile, tmp_8_fu_430_p4, "tmp_8_fu_430_p4");
    sc_trace(mVcdFile, trunc_ln104_1_fu_440_p1, "trunc_ln104_1_fu_440_p1");
    sc_trace(mVcdFile, icmp_ln104_3_fu_468_p2, "icmp_ln104_3_fu_468_p2");
    sc_trace(mVcdFile, icmp_ln104_2_fu_462_p2, "icmp_ln104_2_fu_462_p2");
    sc_trace(mVcdFile, or_ln104_fu_456_p2, "or_ln104_fu_456_p2");
    sc_trace(mVcdFile, or_ln104_1_fu_474_p2, "or_ln104_1_fu_474_p2");
    sc_trace(mVcdFile, and_ln104_fu_480_p2, "and_ln104_fu_480_p2");
    sc_trace(mVcdFile, grp_fu_167_p2, "grp_fu_167_p2");
    sc_trace(mVcdFile, and_ln104_1_fu_486_p2, "and_ln104_1_fu_486_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

i_max_pooling4::~i_max_pooling4() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete lenet_top_fcmp_32dEe_U31;
}

void i_max_pooling4::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void i_max_pooling4::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv5_2;
}

void i_max_pooling4::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln97_fu_237_p2.read(), ap_const_lv1_1))) {
        c_0_reg_86 = c_reg_502.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        c_0_reg_86 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln98_fu_284_p2.read(), ap_const_lv1_1))) {
        h_0_reg_97 = h_reg_520.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln96_fu_173_p2.read(), ap_const_lv1_0))) {
        h_0_reg_97 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(icmp_ln103_fu_378_p2.read(), ap_const_lv1_1))) {
        i_0_reg_133 = i_reg_551.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_284_p2.read()))) {
        i_0_reg_133 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_308_p2.read()))) {
        j_0_reg_156 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        j_0_reg_156 = j_reg_564.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(icmp_ln103_fu_378_p2.read(), ap_const_lv1_1))) {
        max_value_0_reg_120 = max_value_1_reg_144.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_284_p2.read()))) {
        max_value_0_reg_120 = ap_const_lv32_D368D4A5;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_308_p2.read()))) {
        max_value_1_reg_144 = max_value_0_reg_120.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        max_value_1_reg_144 = max_value_fu_492_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_237_p2.read()))) {
        w_0_reg_108 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(icmp_ln101_fu_308_p2.read(), ap_const_lv1_1))) {
        w_0_reg_108 = w_reg_538.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln96_fu_173_p2.read(), ap_const_lv1_0))) {
        add_ln104_2_reg_507 = add_ln104_2_fu_213_p2.read();
        add_ln106_reg_512 = add_ln106_fu_231_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln101_fu_308_p2.read()))) {
        add_ln104_4_reg_556 = add_ln104_4_fu_354_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln97_fu_237_p2.read()))) {
        add_ln106_2_reg_530 = add_ln106_2_fu_278_p2.read();
        shl_ln_reg_525 = shl_ln_fu_249_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        c_reg_502 = c_fu_179_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        h_reg_520 = h_fu_243_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_reg_551 = i_fu_314_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        input_load_reg_574 = input_r_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j_reg_564 = j_fu_384_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_284_p2.read()))) {
        shl_ln104_1_reg_543 = shl_ln104_1_fu_296_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        w_reg_538 = w_fu_290_p2.read();
    }
}

void i_max_pooling4::thread_add_ln104_1_fu_390_p2() {
    add_ln104_1_fu_390_p2 = (!zext_ln103_fu_374_p1.read().is_01() || !shl_ln104_1_reg_543.read().is_01())? sc_lv<4>(): (sc_biguint<4>(zext_ln103_fu_374_p1.read()) + sc_biguint<4>(shl_ln104_1_reg_543.read()));
}

void i_max_pooling4::thread_add_ln104_2_fu_213_p2() {
    add_ln104_2_fu_213_p2 = (!zext_ln104_2_fu_209_p1.read().is_01() || !zext_ln104_1_fu_197_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln104_2_fu_209_p1.read()) + sc_biguint<9>(zext_ln104_1_fu_197_p1.read()));
}

void i_max_pooling4::thread_add_ln104_3_fu_329_p2() {
    add_ln104_3_fu_329_p2 = (!zext_ln104_3_fu_325_p1.read().is_01() || !add_ln104_2_reg_507.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln104_3_fu_325_p1.read()) + sc_biguint<9>(add_ln104_2_reg_507.read()));
}

void i_max_pooling4::thread_add_ln104_4_fu_354_p2() {
    add_ln104_4_fu_354_p2 = (!p_shl4_cast_fu_334_p3.read().is_01() || !zext_ln104_4_fu_350_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_shl4_cast_fu_334_p3.read()) + sc_biguint<12>(zext_ln104_4_fu_350_p1.read()));
}

void i_max_pooling4::thread_add_ln104_5_fu_399_p2() {
    add_ln104_5_fu_399_p2 = (!add_ln104_4_reg_556.read().is_01() || !zext_ln104_5_fu_395_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(add_ln104_4_reg_556.read()) + sc_biguint<12>(zext_ln104_5_fu_395_p1.read()));
}

void i_max_pooling4::thread_add_ln104_fu_320_p2() {
    add_ln104_fu_320_p2 = (!shl_ln_reg_525.read().is_01() || !zext_ln101_fu_304_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(shl_ln_reg_525.read()) + sc_biguint<4>(zext_ln101_fu_304_p1.read()));
}

void i_max_pooling4::thread_add_ln106_1_fu_261_p2() {
    add_ln106_1_fu_261_p2 = (!zext_ln106_1_fu_257_p1.read().is_01() || !add_ln106_reg_512.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln106_1_fu_257_p1.read()) + sc_biguint<8>(add_ln106_reg_512.read()));
}

void i_max_pooling4::thread_add_ln106_2_fu_278_p2() {
    add_ln106_2_fu_278_p2 = (!p_shl3_cast_fu_270_p3.read().is_01() || !zext_ln106_2_fu_266_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(p_shl3_cast_fu_270_p3.read()) + sc_biguint<10>(zext_ln106_2_fu_266_p1.read()));
}

void i_max_pooling4::thread_add_ln106_3_fu_364_p2() {
    add_ln106_3_fu_364_p2 = (!add_ln106_2_reg_530.read().is_01() || !zext_ln106_3_fu_360_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(add_ln106_2_reg_530.read()) + sc_biguint<10>(zext_ln106_3_fu_360_p1.read()));
}

void i_max_pooling4::thread_add_ln106_fu_231_p2() {
    add_ln106_fu_231_p2 = (!zext_ln104_fu_185_p1.read().is_01() || !zext_ln106_fu_227_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln104_fu_185_p1.read()) + sc_biguint<8>(zext_ln106_fu_227_p1.read()));
}

void i_max_pooling4::thread_and_ln104_1_fu_486_p2() {
    and_ln104_1_fu_486_p2 = (and_ln104_fu_480_p2.read() & grp_fu_167_p2.read());
}

void i_max_pooling4::thread_and_ln104_fu_480_p2() {
    and_ln104_fu_480_p2 = (or_ln104_fu_456_p2.read() & or_ln104_1_fu_474_p2.read());
}

void i_max_pooling4::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void i_max_pooling4::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void i_max_pooling4::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void i_max_pooling4::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void i_max_pooling4::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void i_max_pooling4::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void i_max_pooling4::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void i_max_pooling4::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void i_max_pooling4::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln96_fu_173_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void i_max_pooling4::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void i_max_pooling4::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln96_fu_173_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void i_max_pooling4::thread_bitcast_ln104_1_fu_427_p1() {
    bitcast_ln104_1_fu_427_p1 = input_load_reg_574.read();
}

void i_max_pooling4::thread_bitcast_ln104_fu_409_p1() {
    bitcast_ln104_fu_409_p1 = max_value_1_reg_144.read();
}

void i_max_pooling4::thread_c_fu_179_p2() {
    c_fu_179_p2 = (!c_0_reg_86.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(c_0_reg_86.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void i_max_pooling4::thread_h_fu_243_p2() {
    h_fu_243_p2 = (!h_0_reg_97.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(h_0_reg_97.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void i_max_pooling4::thread_i_fu_314_p2() {
    i_fu_314_p2 = (!i_0_reg_133.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i_0_reg_133.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void i_max_pooling4::thread_icmp_ln101_fu_308_p2() {
    icmp_ln101_fu_308_p2 = (!i_0_reg_133.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_133.read() == ap_const_lv2_2);
}

void i_max_pooling4::thread_icmp_ln103_fu_378_p2() {
    icmp_ln103_fu_378_p2 = (!j_0_reg_156.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_156.read() == ap_const_lv2_2);
}

void i_max_pooling4::thread_icmp_ln104_1_fu_450_p2() {
    icmp_ln104_1_fu_450_p2 = (!trunc_ln104_fu_423_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln104_fu_423_p1.read() == ap_const_lv23_0);
}

void i_max_pooling4::thread_icmp_ln104_2_fu_462_p2() {
    icmp_ln104_2_fu_462_p2 = (!tmp_8_fu_430_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_8_fu_430_p4.read() != ap_const_lv8_FF);
}

void i_max_pooling4::thread_icmp_ln104_3_fu_468_p2() {
    icmp_ln104_3_fu_468_p2 = (!trunc_ln104_1_fu_440_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln104_1_fu_440_p1.read() == ap_const_lv23_0);
}

void i_max_pooling4::thread_icmp_ln104_fu_444_p2() {
    icmp_ln104_fu_444_p2 = (!tmp_fu_413_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_413_p4.read() != ap_const_lv8_FF);
}

void i_max_pooling4::thread_icmp_ln96_fu_173_p2() {
    icmp_ln96_fu_173_p2 = (!c_0_reg_86.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(c_0_reg_86.read() == ap_const_lv5_10);
}

void i_max_pooling4::thread_icmp_ln97_fu_237_p2() {
    icmp_ln97_fu_237_p2 = (!h_0_reg_97.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(h_0_reg_97.read() == ap_const_lv3_5);
}

void i_max_pooling4::thread_icmp_ln98_fu_284_p2() {
    icmp_ln98_fu_284_p2 = (!w_0_reg_108.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(w_0_reg_108.read() == ap_const_lv3_5);
}

void i_max_pooling4::thread_input_r_address0() {
    input_r_address0 =  (sc_lv<11>) (zext_ln104_6_fu_404_p1.read());
}

void i_max_pooling4::thread_input_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void i_max_pooling4::thread_j_fu_384_p2() {
    j_fu_384_p2 = (!j_0_reg_156.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(j_0_reg_156.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void i_max_pooling4::thread_max_value_fu_492_p3() {
    max_value_fu_492_p3 = (!and_ln104_1_fu_486_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln104_1_fu_486_p2.read()[0].to_bool())? max_value_1_reg_144.read(): input_load_reg_574.read());
}

void i_max_pooling4::thread_or_ln104_1_fu_474_p2() {
    or_ln104_1_fu_474_p2 = (icmp_ln104_3_fu_468_p2.read() | icmp_ln104_2_fu_462_p2.read());
}

void i_max_pooling4::thread_or_ln104_fu_456_p2() {
    or_ln104_fu_456_p2 = (icmp_ln104_1_fu_450_p2.read() | icmp_ln104_fu_444_p2.read());
}

void i_max_pooling4::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<9>) (zext_ln106_4_fu_369_p1.read());
}

void i_max_pooling4::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void i_max_pooling4::thread_output_r_d0() {
    output_r_d0 = max_value_0_reg_120.read();
}

void i_max_pooling4::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln101_fu_308_p2.read(), ap_const_lv1_1))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void i_max_pooling4::thread_p_shl3_cast_fu_270_p3() {
    p_shl3_cast_fu_270_p3 = esl_concat<8,2>(add_ln106_1_fu_261_p2.read(), ap_const_lv2_0);
}

void i_max_pooling4::thread_p_shl4_cast_fu_334_p3() {
    p_shl4_cast_fu_334_p3 = esl_concat<9,3>(add_ln104_3_fu_329_p2.read(), ap_const_lv3_0);
}

void i_max_pooling4::thread_shl_ln104_1_fu_296_p3() {
    shl_ln104_1_fu_296_p3 = esl_concat<3,1>(w_0_reg_108.read(), ap_const_lv1_0);
}

void i_max_pooling4::thread_shl_ln_fu_249_p3() {
    shl_ln_fu_249_p3 = esl_concat<3,1>(h_0_reg_97.read(), ap_const_lv1_0);
}

void i_max_pooling4::thread_tmp_4_fu_201_p3() {
    tmp_4_fu_201_p3 = esl_concat<5,1>(c_0_reg_86.read(), ap_const_lv1_0);
}

void i_max_pooling4::thread_tmp_5_fu_219_p3() {
    tmp_5_fu_219_p3 = esl_concat<5,2>(c_0_reg_86.read(), ap_const_lv2_0);
}

void i_max_pooling4::thread_tmp_7_fu_342_p3() {
    tmp_7_fu_342_p3 = esl_concat<9,1>(add_ln104_3_fu_329_p2.read(), ap_const_lv1_0);
}

void i_max_pooling4::thread_tmp_8_fu_430_p4() {
    tmp_8_fu_430_p4 = bitcast_ln104_1_fu_427_p1.read().range(30, 23);
}

void i_max_pooling4::thread_tmp_fu_413_p4() {
    tmp_fu_413_p4 = bitcast_ln104_fu_409_p1.read().range(30, 23);
}

void i_max_pooling4::thread_tmp_s_fu_189_p3() {
    tmp_s_fu_189_p3 = esl_concat<5,3>(c_0_reg_86.read(), ap_const_lv3_0);
}

void i_max_pooling4::thread_trunc_ln104_1_fu_440_p1() {
    trunc_ln104_1_fu_440_p1 = bitcast_ln104_1_fu_427_p1.read().range(23-1, 0);
}

void i_max_pooling4::thread_trunc_ln104_fu_423_p1() {
    trunc_ln104_fu_423_p1 = bitcast_ln104_fu_409_p1.read().range(23-1, 0);
}

void i_max_pooling4::thread_w_fu_290_p2() {
    w_fu_290_p2 = (!w_0_reg_108.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(w_0_reg_108.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void i_max_pooling4::thread_zext_ln101_fu_304_p1() {
    zext_ln101_fu_304_p1 = esl_zext<4,2>(i_0_reg_133.read());
}

void i_max_pooling4::thread_zext_ln103_fu_374_p1() {
    zext_ln103_fu_374_p1 = esl_zext<4,2>(j_0_reg_156.read());
}

void i_max_pooling4::thread_zext_ln104_1_fu_197_p1() {
    zext_ln104_1_fu_197_p1 = esl_zext<9,8>(tmp_s_fu_189_p3.read());
}

void i_max_pooling4::thread_zext_ln104_2_fu_209_p1() {
    zext_ln104_2_fu_209_p1 = esl_zext<9,6>(tmp_4_fu_201_p3.read());
}

void i_max_pooling4::thread_zext_ln104_3_fu_325_p1() {
    zext_ln104_3_fu_325_p1 = esl_zext<9,4>(add_ln104_fu_320_p2.read());
}

void i_max_pooling4::thread_zext_ln104_4_fu_350_p1() {
    zext_ln104_4_fu_350_p1 = esl_zext<12,10>(tmp_7_fu_342_p3.read());
}

void i_max_pooling4::thread_zext_ln104_5_fu_395_p1() {
    zext_ln104_5_fu_395_p1 = esl_zext<12,4>(add_ln104_1_fu_390_p2.read());
}

void i_max_pooling4::thread_zext_ln104_6_fu_404_p1() {
    zext_ln104_6_fu_404_p1 = esl_zext<64,12>(add_ln104_5_fu_399_p2.read());
}

void i_max_pooling4::thread_zext_ln104_fu_185_p1() {
    zext_ln104_fu_185_p1 = esl_zext<8,5>(c_0_reg_86.read());
}

void i_max_pooling4::thread_zext_ln106_1_fu_257_p1() {
    zext_ln106_1_fu_257_p1 = esl_zext<8,3>(h_0_reg_97.read());
}

void i_max_pooling4::thread_zext_ln106_2_fu_266_p1() {
    zext_ln106_2_fu_266_p1 = esl_zext<10,8>(add_ln106_1_fu_261_p2.read());
}

void i_max_pooling4::thread_zext_ln106_3_fu_360_p1() {
    zext_ln106_3_fu_360_p1 = esl_zext<10,3>(w_0_reg_108.read());
}

void i_max_pooling4::thread_zext_ln106_4_fu_369_p1() {
    zext_ln106_4_fu_369_p1 = esl_zext<64,10>(add_ln106_3_fu_364_p2.read());
}

void i_max_pooling4::thread_zext_ln106_fu_227_p1() {
    zext_ln106_fu_227_p1 = esl_zext<8,7>(tmp_5_fu_219_p3.read());
}

void i_max_pooling4::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln96_fu_173_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln97_fu_237_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln98_fu_284_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln101_fu_308_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(icmp_ln103_fu_378_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}

}

